with open('save.txt', 'w') as fopen:
    fopen.write('Line 1')
    fopen.write('Line 2')
    fopen.write('Line 3')
    fopen.write('Line 4')
    print()
    fopen.write('Line 1\n')
    fopen.write('Line 2\n')
    fopen.write('Line 3\n')
    fopen.write('Line 4\n')
